services:
  - type: web
    name: electiq
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "backend.app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
